add support for AOMP env variable and remove shifting by number of dropped bits

diff --git a/utils/bin/openmpi_set_cu_mask b/utils/bin/openmpi_set_cu_mask
--- a/utils/bin/openmpi_set_cu_mask
+++ b/utils/bin/openmpi_set_cu_mask
@@ -32,6 +32,20 @@ if [ -z "$_num_local_procs" ] ; then
    exit 1
 fi
 
+AOMP=${AOMP:-_AOMP_INSTALL_DIR_}
+if [ ! -d $AOMP ] ; then
+   AOMP="_AOMP_INSTALL_DIR_"
+fi
+if [ ! -d $AOMP ] ; then
+   echo "ERROR: AOMP not found at $AOMP"
+   echo "       Please install AOMP or correctly set env-var AOMP"
+   exit 1
+fi
+if [ ! -f $AOMP/bin/rocminfo ] ; then
+   echo "ERROR: Could not find binary $AOMP/bin/rocminfo"
+   echo "       Please correct the installation of AOMP"
+   exit 1
+fi
 # Assume the number of GPU cus is maximum CU count of all agents 
 _number_of_CUs=0
 for last_cu_count in `$AOMP/bin/rocminfo | grep "Compute Unit:" | cut -d":" -f2` ; do
@@ -53,9 +67,8 @@ if [ $_rem != 0 ] ; then
 fi
 
 #  Calculate the CU mask
-_number_of_bits_to_drop=$(( 64 - $_number_of_CUs ))
 _bits_to_set=$(($_number_of_CUs/$_num_local_procs))
-_bits_to_shift=$((($_local_proc_num * $_bits_to_set) + $_number_of_bits_to_drop  ))
+_bits_to_shift=$(($_local_proc_num * $_bits_to_set))
 _unshifted_bits=$((( 2 ** $_bits_to_set ) - 1 ))
 _mask_decimal=$(($_unshifted_bits<<$_bits_to_shift))
 _mask=$( printf "0x%016x" $_mask_decimal ) 
