remove restriction that CU count must be divisible by np

diff --git a/utils/bin/openmpi_set_cu_mask b/utils/bin/openmpi_set_cu_mask
--- a/utils/bin/openmpi_set_cu_mask
+++ b/utils/bin/openmpi_set_cu_mask
@@ -24,6 +24,7 @@
 #  Updated on 3/11 by Greg Rodgers to work with multiple devices
 #  Copyright (c) 2022 ADVANCED MICRO DEVICES, INC.
 
+
 PROGVERSION=X.Y-Z
 function version(){
    echo $0 version $PROGVERSION
@@ -54,15 +55,16 @@ if [ ! -f $AOMP/bin/rocminfo ] ; then
    exit 1
 fi
 # Get number of GPUS from rocm_agent_enumerator
-_actual_num_devices=`$AOMP/bin/rocm_agent_enumerator | wc -l`
-_actual_num_devices=$(( $_actual_num_devices - 1 ))
-if [[ $_actual_num_devices -lt 1  ]] ; then
+_available_devices=`$AOMP/bin/rocm_agent_enumerator | wc -l`
+_available_devices=$(( $_available_devices - 1 ))
+if [[ $_available_devices -lt 1  ]] ; then
    echo "ERROR: No GPUS available"
    exit 1
 fi
+_available_devices=1
 
 # Find GPU with largest number of CUs
-_number_of_CUs=0
+_actual_number_of_CUs_per_GPU=0
 for last_cu_count in `$AOMP/bin/rocminfo | grep -E "Compute Unit:| Device Type:" | cut -d":" -f2` ; do
   if [ $last_cu_count == "CPU" ] ; then 
      _last_device_type_was_gpu=0
@@ -70,53 +72,74 @@ for last_cu_count in `$AOMP/bin/rocminfo | grep -E "Compute Unit:| Device Type:"
      _last_device_type_was_gpu=1
   else
      if [[ $_last_device_type_was_gpu == 1 ]] ; then
-        if [[ $last_cu_count -gt $_number_of_CUs ]] ; then
-            _number_of_CUs=$last_cu_count
+	if [[ $_actual_number_of_CUs_per_GPU == 0 ]] ; then
+           _actual_number_of_CUs_per_GPU=$last_cu_count
+	else
+           if [[ $_actual_number_of_CUs_per_GPU != $last_cu_count ]] ; then
+              echo "ERROR: Defective node! The cu_count for each GPU must be identical"
+	      echo "       Last CU count : $last_cu_count"
+	      echo "       Previous CU count : $_actual_number_of_CUs_per_GPU"
+	      echo "       Number of GPUs : $_available_devices"
+	      exit 1
+           fi
         fi
      fi
   fi
 done
 
+if [ $_available_devices -gt  $_num_local_ranks ] ; then
+   _num_devices=$_num_local_ranks
+else
+   _num_devices=$_available_devices
+fi
+
 # Calculate number of GPUs to use to evenly spread ranks across GPUs
-_num_devices=$_actual_num_devices
-_rem1=$(( $_num_local_ranks % $_num_devices ))
-while [ $_rem1 != 0 ] ; do
-   _num_devices=$(( $_num_devices - 1 ))
-   _rem1=$(( $_num_local_ranks % $_num_devices ))
+_uncovered_ranks=$(( $_num_local_ranks % $_num_devices ))
+_num_local_ranks_per_GPU=$(( $_num_local_ranks / $_num_devices ))
+if [ $_uncovered_ranks != 0 ] ; then
+   _num_local_ranks_per_GPU=$(( $_num_local_ranks_per_GPU + 1 ))
+fi
+_device_num=$(( $_local_rank_num / $_num_local_ranks_per_GPU ))
+_number_of_CUs_per_GPU=$_actual_number_of_CUs_per_GPU
+_rem2=$(( $_number_of_CUs_per_GPU % _num_local_ranks_per_GPU ))
+# Lower number of CUs till divisible by number of ranks per GPU
+while [ $_rem2 != 0 ] ; do
+   _number_of_CUs_per_GPU=$(( $_number_of_CUs_per_GPU - 1 ))
+   _rem2=$(( $_number_of_CUs_per_GPU % _num_local_ranks_per_GPU ))
 done
-if [ $_actual_num_devices != $_num_devices ] ; then
-   # give warning on rank 0 if number of devices were trimmed
-   if [ $_local_rank_num == 0 ] ; then
-      echo "WARNING: The number of MPI ranks cannot be divided by available GPUs"
-      echo "         The number of MPI ranks: $_num_local_ranks"
-      echo "         Available GPUs:          $_actual_num_devices"
-      echo "         Selected number of GPUs: $_num_devices"
+_number_CUs_per_rank=$(( $_number_of_CUs_per_GPU / $_num_local_ranks_per_GPU ))
+
+# Diagnostics:
+if [ $_local_rank_num == 0 ] ; then
+   echo "   RANKS: $_num_local_ranks"
+   echo "   AVAILALBLE GPUS:  $_available_devices"
+   echo "   USED GPUS:        $_num_devices"
+   echo "   SLOTS PER GPU:    $_num_local_ranks_per_GPU"
+   echo "   NUM CUs PER GPU:  $_actual_number_of_CUs_per_GPU"
+   echo "   USED CUs PER GPU: $_number_of_CUs_per_GPU"
+   echo "   CUs per SLOT:     $_number_CUs_per_rank"
+   # calculate excess ranks
+   wasted_CUs_on_each_GPU=$(( $_actual_number_of_CUs_per_GPU - $_number_of_CUs_per_GPU ))
+   _total_GPU_slots=$(( $_num_local_ranks_per_GPU * $_num_devices ))
+   _total_wasted_slots=$(( $_total_GPU_slots - $_num_local_ranks ))
+   if [ $wasted_CUs_on_each_GPU != 0 ] || [ $_total_wasted_slots != 0 ] ; then
+      echo
+      echo "   WASTED CUs per GPU:       $wasted_CUs_on_each_GPU"
+      echo "   WASTED SLOTS:             $_total_wasted_slots"
+      echo "   WASTED GPUS:              $(( $_total_wasted_slots / $_num_local_ranks_per_GPU )) "
+      echo "   WASTED SLOTS ON LAST GPU: $(( $_total_wasted_slots % $_num_local_ranks_per_GPU )) "
    fi
 fi
-_total_number_of_CUs=$(( $_num_devices * $_number_of_CUs ))
-_num_local_ranks_per_GPU=$(( $_num_local_ranks / $_num_devices ))
-_number_of_CUs_per_GPU=$(( $_total_number_of_CUs / $_num_devices ))
-_device_num=$(( $_local_rank_num / $_num_local_ranks_per_GPU ))
-_relative_rank_num=$(( $_local_rank_num / $_num_devices ))
 
-# This script is only tested where CUs can be divided evenly across MPI ranks
-_rem2=$(($_total_number_of_CUs%_num_local_ranks))
-if [ $_rem2 != 0 ] ; then
-   echo "ERROR: The total number of CUs ($_total_number_of_CUs) can not be divided by $_num_local_ranks"
-   echo "       The number of CUs per GPU is: $_number_of_CUs"
-   echo "       The number of GPUs is: $_num_devices"
-   exit 1
-fi
-
-#  Build the CU mask for this rank
-_bits_to_set=$(( $_number_of_CUs / $_num_local_ranks_per_GPU ))
+#  Build the CU mask for this rank, bits_to_set equals _number_CUs_per_rank
+_bits_to_set=$(( $_number_of_CUs_per_GPU / $_num_local_ranks_per_GPU ))
 #  This formula keeps adjacent ranks on same GPU which should be preferred
 _bits_to_shift=$(( ( $_local_rank_num * $_bits_to_set) - ( _device_num * $_number_of_CUs_per_GPU) ))
 # use bc because these values can be very large
 _unshifted_bits=`echo "(2 ^ $_bits_to_set) - 1" | bc`
 _mask=`echo "obase=16; $_unshifted_bits * (2 ^ $_bits_to_shift)" | bc`
 # Calculate the number of leading zeros needed for this mask
-_lz=$(( ( $_number_of_CUs / 4 ) - ${#_mask} + 1 ))
+_lz=$(( ( $_number_of_CUs_per_GPU / 4 ) - ${#_mask} + 1 ))
 for i in `seq 1 $_lz` ; do
     _mask="0$_mask"
 done
@@ -124,7 +147,7 @@ _mask="0x$_mask"
 
 export ROCM_VISIBLE_DEVICES=$_device_num
 export HSA_CU_MASK=$ROCM_VISIBLE_DEVICES:$_mask
-printf "rank %4s HSA_CU_MASK %20s\n" $_local_rank_num $HSA_CU_MASK
+printf "rank %02d HSA_CU_MASK %20s\n" $_local_rank_num $HSA_CU_MASK
 
 # execute the application
 $*
